main-app/main_app/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('password/', include('generator_password.urls')),
    path('text/', include('text_manipulation.urls')),
    path('todo/', include('todo.urls')),
    
    # Auth
    path('signup/', views.signupuser, name='signupuser'),
    path('logout/', views.logoutuser, name='logoutuser'),
    path('login/', views.loginuser, name='loginuser'),

    # Index page
    path('', views.index_page, name='index-page'),
]

main-app/todo/urls.py
from django.urls import path
from todo import views


app_name = 'todo'
urlpatterns = [
    path('', views.current_todos, name='current-todos'),
    path('completed/', views.completed_todos, name='completed-todos'),
    path('create/', views.create_todo, name='create-todo'),
    path('<int:todo_pk>/', views.view_todo, name='view-todo'),
    path('<int:todo_pk>/complete/', views.complete_todo, name='complete-todo'),
    path('<int:todo_pk>/delete/', views.delete_todo, name='delete-todo'),
]

main-app/todo/models.py
from django.db import models
from django.contrib.auth.models import User


class Todo(models.Model):

    title = models.CharField(max_length=100)
    memo = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    datecompleted = models.DateTimeField(blank=True, null=True)
    important = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return f"{self.user}: {self.title}"

main-app/todo/forms.py
from django.forms import ModelForm
from todo.models import Todo


class TodoForm(ModelForm):
    class Meta:
        model = Todo
        fields = ['title', 'memo', 'important']

main-app/todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from todo.forms import TodoForm
from todo.models import Todo
from django.utils import timezone
from django.contrib.auth.decorators import login_required


@login_required
def current_todos(request):
    """ Текущие задания """

    context = {}

    todos = Todo.objects.filter(user=request.user, datecompleted__isnull=True) \
                        .order_by('-important', '-created')
    context['todos'] = todos
    return render(request, 'todo/current_todos.html', context)


@login_required
def create_todo(request):
    """ Создание задания """
    
    context = {}

    if request.method == 'GET':
        context['form'] = TodoForm()
        return render(request, 'todo/create_todo.html', context)
    else:
        try:
            form = TodoForm(request.POST)
            newtodo = form.save(commit=False)
            newtodo.user = request.user
            newtodo.save()
        except ValueError:
            context['form'] = TodoForm()
            context['error'] = 'Не верно введенные данные. Попробуйте заново!'
            return render(request, 'todo/create_todo.html', context)
        return redirect('todo:current-todos')


@login_required
def view_todo(request, todo_pk):
    """ Отображение конкретного """

    context = {}

    todo = get_object_or_404(Todo, pk=todo_pk, user=request.user)
    context['todo'] = todo

    if request.method == 'GET':
        context['form'] = TodoForm(instance=todo)

        return render(request, 'todo/view_todo.html', context)
    else:
        try:
            form = TodoForm(request.POST, instance=todo)
            form.save()
            return redirect('todo:current-todos')

        except ValueError:
            context['form'] = form
            context['error'] = 'Что-то пошло не так... Попробуйте заполнить поля заново'
            return render(request, 'todo/viewtodo.html', context)



@login_required
def complete_todo(request, todo_pk):
    """ Выполнить задание """

    context = {}

    todo = get_object_or_404(Todo, pk=todo_pk, user=request.user)
    if request.method == "POST":
        todo.datecompleted = timezone.now()
        todo.save()
        return redirect('todo:current-todos')


@login_required
def delete_todo(request, todo_pk):
    """ Удалить задание """

    context = {}

    todo = get_object_or_404(Todo, pk=todo_pk, user=request.user)
    if request.method == "POST":
        todo.delete()
        return redirect('todo:current-todos')


@login_required
def completed_todos(request):

    context = {}
    todos = Todo.objects.filter(user=request.user, datecompleted__isnull=False) \
                        .order_by('-datecompleted')
    context['todos'] = todos
    return render(request, 'todo/completed_todos.html', context)

main-app/todo/templates/todo/_base_todo.html
{% extends 'core/base.html' %}

{% block nav_list_link %}
    <li class="nav-item">
        <a class="nav-link ml-2 mr-2" href="{% url 'todo:completed-todos' %}">Выполненые задания</a> 
    </li>
    <li class="nav-item">
        <a class="nav-link ml-2 mr-2" href="{% url 'todo:current-todos' %}">Текущие задания</a> 
    </li>
    <li class="nav-item">
        <a class="nav-link ml-2 mr-2" href="{% url 'todo:create-todo' %}">Создать задание</a>
    </li>
    
{% endblock nav_list_link %}
{% block content %}

    {% block content_page %}
    
    {% endblock %}

{% endblock content %}

main-app/todo/templates/todo/completed_todos.html
{% extends 'todo/_base_todo.html' %}
{% load date_timesince %}
{% block content_page %}

<div>
    <h2 class="text-center alert">Все выполненные задания</h2>
</div>
{% if todos %}
<div class="row justify-content-sm-center">
    <div class="list-group col-md-8 ">
        {% for todo in todos %}
            <a href="{% url 'todo:view-todo' todo.id %}" class="list-group-item list-group-item-action border flex-column mb-4 hover {% if todo.important %}impt{% endif %}" 
                >
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{todo.title}}</h5>

                </div>
                {% if todo.memo %}
                    <p class="ml-4 mb-1">{{ todo.memo|truncatechars:200 }}</p>
                {% endif %}

                <div class="d-flex w-100 justify-content-end">
                    <small class="pr-4">Создано: {{ todo.created|date:"M, j Y H:i" }}</small>
                    <small class="pr-4">Выполнено: {{ todo.datecompleted|date:"M, j Y H:i" }}</small>
                    

                </div>
            </a>
        {% endfor %}
    </div>
</div>
{% else %}
<div>
    <h4 class="text-center mb-4 mt-4 pb-4 pt-4">Ни одно задание еще не выполнено!</h4>
</div>
{% endif %}
<div class="mt-2 mb-4 text-center">
    <a href="{% url 'todo:current-todos'%}" class="pl-2 pr-2">Текущие задания</a> |
    <a href="{% url 'todo:create-todo'%}" class="pl-2 pr-2">Создать новое задание</a>
</div>
{% endblock %}
{% block style_add %}
<style>
    .impt{
        background-color: rgba(204, 78, 78, 0.1);
    }
    .hover:hover{
        background-color: rgba(70, 226, 140, 0.1);
    }
</style>
{% endblock style_add %}

main-app/todo/templates/todo/create_todo.html
{% extends 'todo/_base_todo.html' %}

{% block content_page %}
<div>
    <h2 class="text-center alert">Создание нового задания</h2>
</div>

<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        {% if error %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="title">Название<sup style="color: red;" title="Обязательно для заполнения">*</sup></label>
                <input type="text" name="title" class="form-control" id="title" required>
            </div>
            <div class="form-group">
                <label for="memo">Описание</label>
                <textarea name="memo" class="form-control" id="memo" ></textarea>
            </div>
            <div class="form-group form-check">
                <input type="checkbox" name="important" class="form-check-input" id="important">
                <label class="form-check-label" for="important">Важно?</label>
            </div>
            <button type="submit" class="btn btn-primary">Создать</button>
        </form>
    </div>
</div>

<div class="mt-4 pt-4 mb-4 text-center">
    <a href="{% url 'todo:current-todos'%}" class="pl-2 pr-2">Текущие задания</a> |
    <a href="{% url 'todo:completed-todos'%}" class="pl-2 pr-2">Выполненые задания</a>
</div>

{% endblock %}

main-app/todo/templates/todo/current_todos.html
{% extends 'todo/_base_todo.html' %}

{% block content_page %}

<div>
    <h2 class="text-center alert">Текущие задачи</h2>
</div>

<div>
    <ul>
    {% for todo in todos %}
        <li>
            {% if todo.important %}
                <span style="color: red; font-weight: bold;"><i class="fa fa-exclamation"></i>
            {% else %}
                <span>
            {% endif %}
                <a href="{% url 'todo:view-todo' todo.id %}">{{todo.title}}</a></span>
                {% if todo.memo %}
                 - {{ todo.memo|truncatechars:20 }}
                {% endif %}
        </li>
    {% endfor %}
    </ul>
</div>

<div class="mt-4">
    <a href="{% url 'todo:create-todo'%}">Создать новое задание</a>
</div>

{% endblock %}

main-app/todo/templates/todo/view_todo.html
{% extends 'todo/_base_todo.html' %}

{% block content_page %}
    <div>
        <h2 class="text-center alert">Задание</h2>
    </div>    

    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">Название<sup style="color: red;" title="Обязательно для заполнения">*</sup></label>
                    <input type="text" name="title" class="form-control" id="title" value="{{ todo.title }}" required>
                </div>
                <div class="form-group">
                    <label for="memo">Описание</label>
                    <textarea name="memo" rows="5" class="form-control" id="memo" >{{ todo.memo }}</textarea>
                </div>
                <div class="form-group form-check">
                    <input type="checkbox" name="important" class="form-check-input" id="important" {% if todo.important %}checked{% endif %}>
                    <label class="form-check-label" for="important">Важно?</label>
                </div>
                <button type="submit" class="btn btn-primary">Изменить</button>
                <button type="button" class="btn btn-success" onclick="$('#complete').click()">Сделано!</button>
                <button type="button" class="btn btn-danger" onclick="$('#delete').click()">Удалить</button>
            </form>
        </div>
    </div>
    {% if todo.datecompleted is None %}
        <form style='display: none;' method="POST" action="{% url 'todo:complete-todo' todo.id %}">
            {% csrf_token %}
            <button id="complete" type="submit">Сделано!</button>
        </form>
    {% else %}
        <button style='display: none;' id="complete" type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
            Сделано!
        </button>
    {% endif %}
    <form style='display: none;' method="POST" action="{% url 'todo:delete-todo' todo.id %}">
        {% csrf_token %}
        <button id="delete" type="submit">Удалить</button>
    </form>



    <div class="mt-4 pt-4 mb-4 text-center">
        <a href="{% url 'todo:current-todos'%}" class="pl-2 pr-2">Текущие задания</a> |
        <a href="{% url 'todo:completed-todos'%}" class="pl-2 pr-2">Выполненые задания</a>
    </div>

  
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Информация</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Это задание уже находится в выполненных!
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
        </div>
      </div>
    </div>
  </div>
      
{% endblock %}


{% block script_add %}
  {% endblock script_add %}