main-app/generator_password/urls.py
from django.urls import path
from generator_password import views


app_name = 'password-app'
urlpatterns = [
    path('', views.gen_pass, name='password'),
]

main-app/main_app/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('password/', include('generator_password.urls')),
    path('text/', include('text_manipulation.urls')),
    path('todo/', include('todo.urls')),
    
    # Auth
    path('signup/', views.signupuser, name='signupuser'),
    path('logout/', views.logoutuser, name='logoutuser'),
    path('login/', views.loginuser, name='loginuser'),

    # Index page
    path('', views.index_page, name='index-page'),
]

main-app/text_manipulation/urls.py
from django.urls import path
from text_manipulation import views


app_name = 'text-manipulation'
urlpatterns = [
    path('', views.count_smt_in_text, name='count-smt'),
]

main-app/todo/urls.py
from django.urls import path
from todo import views


app_name = 'todo'
urlpatterns = [
    path('', views.current_todos, name='current-todos'),
    path('completed/', views.completed_todos, name='completed-todos'),
    path('create/', views.create_todo, name='create-todo'),
    path('<int:todo_pk>/', views.view_todo, name='view-todo'),
    path('<int:todo_pk>/complete/', views.complete_todo, name='complete-todo'),
    path('<int:todo_pk>/delete/', views.delete_todo, name='delete-todo'),
]

main-app/core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required


def index_page(request):
    """ Стартовая страница """

    return render(request, 'core/index.html')


def signupuser(request):
    """ Регистрация пользователя """

    context = {}
    if request.method == 'GET':
        context['form'] = UserCreationForm()
        return render(request, 'core/signupuser.html', context)
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
                login(request, user)
                return redirect('index-page')
            except IntegrityError:
                context['error'] = f'Пользователь с юзернеймом {request.POST["username"]} уже существует. Пожалуйста, выберите другое имя!'
                context['form'] = UserCreationForm()
        else:
            context['error'] = 'Пароли не совпадают!'
            context['form'] = UserCreationForm()

    return render(request, 'core/signupuser.html', context)


@login_required
def logoutuser(request):
    """ Выйти из аккаунта """

    if request.method == 'POST':
        logout(request)
        return redirect('index-page')


def loginuser(request):
    """ Логин """

    context = {}
    context['form'] = AuthenticationForm()

    if request.GET:  
        next = request.GET['next']

    if request.method == 'POST':
        
        user = authenticate(request, username=request.POST["username"], password=request.POST["password"])
        if user is None:
            context['error'] = 'Логин или пароль не подходят!'
        else:
            login(request, user)
            if next:
                return redirect(next)
            return redirect('index-page')

    return render(request, 'core/loginuser.html', context)

main-app/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/fontawesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/brands.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/solid.min.css">
    {% block link_add %}{% endblock link_add %}
    <title>{% block title %}Django small apps{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-light navbar-expand-md bg-light justify-content-md-center justify-content-start">
        <button class="navbar-toggler ml-1 mr-4" type="button" data-toggle="collapse" data-target="#collapsingNavbar2">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand d-inline" href="{% url 'index-page' %}">SCRAP-HEAP</a>
        
        
        <div class="navbar-collapse collapse justify-content-between align-items-center w-100" id="collapsingNavbar2">
            <ul class="navbar-nav mx-auto text-md-center">
                {% block nav_list_link %}
                    <li class="nav-item">
                        <a class="nav-link ml-2 mr-2" href="{% url 'password-app:password' %}">Генератор пароля</a> 
                    </li>
                    <li class="nav-item">
                        <a class="nav-link ml-2 mr-2" href="{% url 'todo:current-todos' %}">Todo приложение</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link ml-2 mr-2" href="{% url 'text-manipulation:count-smt' %}">Работа с текстом</a> 
                    </li>
                {% endblock nav_list_link %}
            </ul>
            <ul class="nav navbar-nav flex-row justify-content-md-center justify-content-start flex-nowrap">
                {% if user.is_authenticated %}
                <li class="nav-item nav-link">Привет, {{user}}!</li>
                <li class="nav-item ">
                    <form action="{% url 'logoutuser' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn nav-link" title="Выйти с аккаунта"><i class="fas fa-sign-out-alt"></i></button>
                    </form>
                </li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'signupuser' %}"><i class="fas fa-user-plus"></i> Регистрация</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'loginuser' %}"><i class="fas fa-sign-in-alt"></i> Ввойти</a></li>
                {% endif %}
            </ul>
        </div>
        
    
    </nav>
    

    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.0/js/bootstrap.min.js"></script>
    {% block script_add %}{% endblock script_add %}
    {% block style_add %}{% endblock style_add %}

</body>
</html>

main-app/core/templates/core/index.html
{% extends 'core/base.html' %}



{% block content %}
<div>
    <div class="text text-center alert">
        <h2>Главная страница</h2>
    </div>
    <div class="link alert">
        <a href="{% url 'password-app:password' %}">Генератор пароля</a>
    </div>
    <div class="link alert">
        <a href="{% url 'todo:current-todos' %}">ToDo приложение</a>
    </div>
    <div class="link alert">
        <a href="{% url 'text-manipulation:count-smt' %}">Работа с текстом</a>
    </div>
</div>


{% endblock content %}

main-app/core/templates/core/loginuser.html
{% extends 'core/base.html' %}

{% block content %}

    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>Вход в аккаунт</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Имя пользователя</label>
                    <input type="text" name="username" class="form-control" id="username">
                </div>
                <div class="form-group">
                    <label for="password">Пароль</label>
                    <input type="password" name="password" class="form-control" id="password">
                </div>
                <button type="submit" class="btn btn-primary">Войти</button>
            </form>
            <hr>
            <div class="text-center">
                Новый аккаунт? <a href="{% url 'signupuser' %}">Зарегистрироваться здесь</a>
            </div>
        </div>
    </div>
{% endblock %}

main-app/core/templates/core/signupuser.html
{% extends 'core/base.html' %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>Регистрация пользователя</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Имя пользователя</label>
                    <input type="text" name="username" class="form-control" id="username" aria-describedby="usernameHelp">
                    <small id="usernameHelp" class="form-text text-muted">Имя пользователя должно быть уникальным. Мы дадим вам знать, если кто-то занял это имя.</small>
                </div>
                <div class="form-group">
                    <label for="password1">Пароль</label>
                    <input type="password" name="password1" class="form-control" id="password1">
                </div>
                <div class="form-group">
                    <label for="password2">Подтверждение пароля</label>
                    <input type="password" name="password2" class="form-control" id="password2">
                </div>
                <button type="submit" class="btn btn-primary">Регистрация</button>
            </form>
            <hr>
            <div class="text-center">
                У Вас уже есть аккаунт? <a href="{% url 'loginuser' %}">Войти здесь</a>
            </div>
        </div>
    </div>

{% endblock %}